[package]
name = "tpm-luks"
description = "Automate LUKS keys stored in TPM"
version = "0.1.0"
edition = "2021"
authors = ["Oli Dacombe <olidacombe@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
once_cell = "1.13.0"
tracing = "0.1.34"
tss-esapi = "7.1.0"

[dev-dependencies]
eyre = "0.6.8"


[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

