FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y \
	build-essential \
	curl \
	git \
	libcryptsetup-dev \
	libtss2-dev \
	musl-dev \
	musl-tools \
	pkg-config \
	swtpm \
	swtpm-tools \
	tss2 \
	  zlib1g-dev \
  cmake \
  make \
  g++ \
  curl \
  ca-certificates \
  xutils-dev \
  libpq-dev \
  libssl-dev \ 
  --no-install-recommends

ENV MUSL_PREFIX=/musl
RUN mkdir /workdir && mkdir $MUSL_PREFIX
WORKDIR /libworkdir

RUN ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/x86_64-linux-musl/asm && \
    ln -s /usr/include/asm-generic /usr/include/x86_64-linux-musl/asm-generic && \
    ln -s /usr/include/linux /usr/include/x86_64-linux-musl/linux

ENV OPENSSL_VER="1.1.1q"
RUN curl -sL https://www.openssl.org/source/openssl-${OPENSSL_VER}.tar.gz | tar xz

RUN cd openssl-${OPENSSL_VER} && \
    CC="musl-gcc -fPIE -pie" LDFLAGS="-L/musl/lib/" CFLAGS="-I/musl/include" ./Configure no-shared no-async --prefix=$MUSL_PREFIX --openssldir=$MUSL_PREFIX/ssl linux-x86_64 && \
    make depend && make -j$(nproc) && make install_sw

