FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y \
	bash \
	build-essential \
	curl \
	git \
	libcryptsetup-dev \
	libtss2-dev \
	pkg-config \
	swtpm \
	swtpm-tools \
	tss2

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
