FROM olidacombe/tpm-luks-ci AS rust

RUN cargo install cargo-chef

WORKDIR /workdir

FROM rust AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM rust AS builder
COPY --from=planner /workdir/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json

COPY . .
RUN cargo build --release

RUN mv /workdir/target/release/tpm-luks /
