FROM alpine:latest

RUN apk add --no-cache \
alpine-sdk \
autoconf-archive \
	curl \
	git \
  cmake \
  cryptsetup-dev \
  libtool \
  m4 \
  make \
  openssl-dev \
  pkgconfig \
  	tpm2-tss-dev \
  	tpm2-tss-static \
  g++ \
    autoconf \
  iproute2 \
  gcc \
  linux-headers \
  automake


# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# .cargo/bin in PATH is needed for running cargo, rustup etc.
ENV PATH=/root/.cargo/bin:$PATH

ENV RUSTFLAGS="-C target-feature=+crt-static"
ENV PKG_CONFIG_ALL_STATIC=true

WORKDIR /workdir

# HINT:
# docker build -t tpm-luks-build -f Dockerfile-build . && docker run -it --rm -v $PWD:/workdir tpm-luks-build cargo build --release --target=x86_64-unknown-linux-musl -vv && ls -l target/x86_64-unknown-linux-musl/release/tpm-luks && ldd target/x86_64-unknown-linux-musl/release/tpm-luks
