FROM olidacombe/tpm-luks-ci

RUN apt-get update
RUN apt-get install -y \
	musl-dev \
	musl-tools

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo install cargo-watch

CMD ["/bin/bash", "-l"]
