FROM olidacombe/tpm-luks-ci AS rust

### Rust
# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# .cargo/bin in PATH is needed for running cargo, rustup etc.
ENV PATH=/root/.cargo/bin:$PATH

RUN /root/.cargo/bin/cargo install cargo-chef

WORKDIR /workdir

FROM rust AS planner
COPY . .
RUN /root/.cargo/bin/cargo chef prepare --recipe-path recipe.json

FROM rust AS builder
COPY --from=planner /workdir/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json

COPY . .
RUN cargo build --release

RUN mv /workdir/target/release/tpm-luks /
