FROM alpine:latest

RUN apk add --no-cache \
	alpine-sdk \
    	bash \
	cryptsetup \
	cryptsetup-dev \
	curl \
	e2fsprogs \
	git \
	tpm2-tss-dev

RUN mkdir /workdir
WORKDIR /workdir

COPY make-luks-image.sh .
