FROM ghcr.io/olidacombe/tpm-luks-static-build AS builder

RUN cargo build --release --target=x86_64-unknown-linux-musl

FROM scratch

COPY --from=builder /workdir/target/x86_64-unknown-linux-musl/release/tpm-luks .
