FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y \
	netcat \
	swtpm \
	swtpm-tools \
	tpm2-abrmd 
COPY swtpm-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

HEALTHCHECK --interval=10s --timeout=2s --retries=3\
	CMD nc -vz localhost 2321 \
	&& nc -vz localhost 2322 \
	|| exit 1

ENTRYPOINT ["/entrypoint.sh"]
